add_newline = false

format = """
$username\
$hostname\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$shell\
$sudo\
$character"""

right_format = """$status"""

[username]
show_always = true
format = "[$user](purple)[@](white bold)"

[hostname]
ssh_only = false
format = "[$hostname](purple) "

[directory]
truncation_length = 0
truncate_to_repo = false
format = '([\[](cyan) [$path]($style)[$read_only]($read_only_style)[\]](cyan) )'
read_only = " "
style = "blue bold"

[git_branch]
format = "[$symbol$branch]($style) "
style = "yellow bold"

[sudo]
disabled = false
format = "[S](yellow bold)"

[shell]
disabled = false
format = "[$indicator](cyan bold) "

[status]
disabled = false
format = "[$status](red) [↵](red)"
