add_newline = false

format = """
$username\
$hostname\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$line_break\
$shell\
$sudo\
$character"""

right_format = """$status"""

##############
#   Normal   #
##############
[username]
show_always = true
format = "[$user](purple)[@](white bold)"

[hostname]
ssh_only = false
format = "[$hostname](purple) "

[directory]
truncation_length = 0
truncate_to_repo = false
format = '([\[](cyan) [$path]($style)[$read_only]($read_only_style)[\]](cyan) )'
read_only = " "
style = "blue bold"

[git_branch]
format = "[$symbol$branch]($style) "
style = "yellow bold"

[sudo]
disabled = false
format = "[S](yellow bold)"

[shell]
disabled = false
format = "[$indicator](cyan bold) "

[status]
disabled = false
format = "[$status ↵](red)"

#################
#   Powerline   #
#################
#[username]
#show_always = true
#format = "[](black)[ ](cyan bg:black)[](black bold bg:black)[ $user](purple bold bg:black)[@](green bold bg:black)"

#[hostname]
#ssh_only = false
#format = "[$hostname ](yellow bold bg:black)[](black bold bg:black)"

#[directory]
#truncation_length = 0
#truncate_to_repo = false
#format = "[ ﱮ ](white bg:black)[$path]($style)[$read_only]($read_only_style)[ ](cyan bg:black)[](purple bg:black)[](green bg:black)[](black) "
#style = "blue bold bg:black"
#read_only = "  "
#read_only_style = "red bg:black"

#[git_branch]
#format = "[$symbol$branch]($style) "
#style = "yellow bold"

#[sudo]
#disabled = false
#format = "[S](yellow bold)"

##[shell]
##disabled = false
##format = "[$indicator](cyan bold) "

#[status]
#disabled = false
#format = "[$status ↵](red)"
