###########################
#        Powerline        #
###########################
#format = """
#[╭─](white bold)\
#[](black)[ ](cyan bg:black)[](black bold bg:black)\
#$username\
#[@](green bold bg:black)\
#$hostname\
#[](black bold bg:black)\
#[ ﱮ ](white bg:black)\
#$directory\
#[ ](black bold bg:black)[ ](black)\
#$git_status\
#$git_branch\
#$git_commit\
#$git_state\
#$git_metrics\
#$line_break\
#[╰─](white bold)\
#$shell\
#$sudo\
#$character\
#"""
#right_format = """$status"""

#add_newline = false

#[username]
#show_always = true
#style_user = "purple bold bg:black"
#style_root = "purple bold bg:black"
#format = "[ $user]($style)"

#[hostname]
#ssh_only = false
#style = "yellow bold bg:black"
#format = "[$hostname ]($style)"

#[directory]
#truncation_length = 0
#truncate_to_repo = false
#format = "[$path]($style)[$read_only]($read_only_style)"
#style = "blue bold bg:black"
#read_only = "  "
#read_only_style = "red bg:black"

#[git_status]
#format = "[$all_status$ahead_behind]($style)"

#[git_branch]
#format = "[$symbol $branch](yellow)"
#symbol=""

#[sudo]
#disabled = false
#format = "[S](yellow bold)"

##[shell]
##disabled = false
##format = "[$indicator](cyan bold) "

#[status]
#disabled = false
#format = "[$status ↵](red)"

#########################
#        Bubbles        #
#########################
format = """
[╭─](fg:#0077C2 bold)\
[](#0077C2)\
$username\
[](bg:#0077C2 fg:#444444)\
$directory\
[](fg:#444444)\
$git_branch\
$git_status\
$line_break\
[╰─](fg:#21C7C7 bold)\
$shell\
$sudo\
$character\
"""
right_format = """
$status\
$c\
$golang\
$haskell\
$java\
$nodejs\
$rust\
$lua\
$python\
$docker_context\
[](fg:#40C4FF)\
$time\
[](fg:#40C4FF)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[username]
show_always = true
style_user = "bg:#0077C2 fg:#FFFFFF"
style_root = "bg:#0077C2 fg:#FFFFFF"
format = '[$user ]($style)'

[directory]
style = "bg:#444444"
format = "[ $path ]($style)[$read_only]($read_only_style)"
read_only = "  "
read_only_style = "red bg:#444444"
truncation_length = 0
truncate_to_repo = false

# Here is how you can shorten some long paths by text replacement
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Pictures"  = " "
"Videos"    = "辶"
"Music"     = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "fg:#3C873A bg:#303030"
format = '[](fg:#303030)[ $symbol ($version) ]($style)[ ](fg:#303030)'

[docker_context]
symbol = " "
style = "fg:#3C873A bg:#06969A"
format = '[](fg:#06969A)[ $symbol $context ]($style)[ ](fg:#06969A)'

[git_branch]
symbol = ""
style = "black bg:#FFFb38"
format = '[ ](fg:#FFFb38)[$symbol $branch ]($style)'

[git_status]
style = "black bg:#FFFb38"
format = '[$all_status$ahead_behind]($style)[](fg:#FFFb38)'

[golang]
symbol = " "
style = "fg:#3C873A bg:#303030"
format = '[](fg:#303030)[ $symbol ($version) ]($style)[ ](fg:#303030)'

[haskell]
symbol = " "
style = "fg:#3C873A bg:#303030"
format = '[](fg:#303030)[ $symbol ($version) ]($style)[ ](fg:#303030)'

[java]
symbol = " "
style = "fg:#3C873A bg:#303030"
format = '[](fg:#303030)[ $symbol ($version) ]($style)[ ](fg:#303030)'

[nodejs]
symbol = ""
style = "fg:#3C873A bg:#303030"
format = '[](fg:#303030)[ $symbol ($version) ]($style)[ ](fg:#303030)'

[rust]
symbol = ""
style = "fg:#3C873A bg:#303030"
format = '[](fg:#303030)[ $symbol ($version) ]($style)[ ](fg:#303030)'

[lua]
symbol = ""
style = "fg:#3C873A bg:#303030"
format = '[](fg:#303030)[ $symbol ($version) ]($style)[ ](fg:#303030)'

[python]
symbol = ""
style = "fg:#3C873A bg:#303030"
format = '[](fg:#303030)[ $symbol ($version) ]($style)[ ](fg:#303030)'

[sudo]
disabled = false
format = "[S](yellow bold)"

[status]
disabled = false
format = "[$status ↵ ](red)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#FFFFFF bg:#40C4FF"
format = '[$time]($style)'
