add_newline = false

format = """
$username\
$hostname\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$line_break\
$shell\
$sudo\
$character"""

right_format = """$status"""

[username]
show_always = true
format = "[$user](green)[@](cyan)"

[hostname]
ssh_only = false
format = "[$hostname](green) "

[directory]
truncation_length = 0
style = "purple bold"

[sudo]
disabled = false
format = "[sudo](red bold)"

[shell]
disabled = false
format = "[$indicator](cyan bold) "

[status]
disabled = false
format = "[$status](red) [↵](red)"
