add_newline = false

format = """
[╭─](white bold)\
$username\
$hostname\
$directory\
$git_status\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$line_break\
[╰─](white bold)\
$shell\
$sudo\
$character\
"""

right_format = """$status"""

##############
#   Normal   #
##############
#[username]
#show_always = true
#format = '([\[](cyan bold)[$user](purple bold)[@](green bold))'

#[hostname]
#ssh_only = false
#format = "[$hostname](yellow bold) "

#[directory]
#truncation_length = 0
#truncate_to_repo = false
#format = '([$path]($style)[$read_only]($read_only_style)[\]](cyan bold) )'
#read_only = " "
#style = "blue bold"

#[git_status]
#format = "[$all_status$ahead_behind]($style)"

#[git_branch]
#format = "[$symbol$branch](yellow) "
#symbol=" "

##[shell]
##disabled = false
##format = "[$indicator](green bold) "

#[sudo]
#disabled = false
#format = "[S](yellow bold)"

#[status]
#disabled = false
#format = "[$status ↵](red)"

#################
#   Powerline   #
#################
[username]
show_always = true
format = "[](black)[ ](cyan bg:black)[](black bold bg:black)[ $user](purple bold bg:black)[@](green bold bg:black)"

[hostname]
ssh_only = false
format = "[$hostname ](yellow bold bg:black)[](black bold bg:black)"

[directory]
truncation_length = 0
truncate_to_repo = false
format = "[ ﱮ ](white bg:black)[$path]($style)[$read_only]($read_only_style)[ ](black bold bg:black)[](black) "
style = "blue bold bg:black"
read_only = "  "
read_only_style = "red bg:black"

[git_status]
format = "[$all_status$ahead_behind]($style)"

[git_branch]
format = "[$symbol$branch](yellow) "
symbol=" "

[sudo]
disabled = false
format = "[S](yellow bold)"

#[shell]
#disabled = false
#format = "[$indicator](cyan bold) "

[status]
disabled = false
format = "[$status ↵](red)"

#format = """
#[╭─](white bold)\
#[](#A82F87)\
#$username\
#[](bg:#A82F87 fg:#DB566E)\
#$directory\
#[](fg:#DB566E)\
#$git_branch\
#$git_status\
#$c\
#$golang\
#$haskell\
#$java\
#$nodejs\
#$rust\
#$lua\
#$python\
#$docker_context\
#$line_break\
#[╰─](white bold)\
#$shell\
#$sudo\
#$character\
#"""
#right_format = """
#$status\
#"""

## Disable the blank line at the start of the prompt
#add_newline = false

#[username]
#show_always = true
#style_user = "bg:#A82F87"
#style_root = "bg:#A82F87"
#format = '[$user ]($style)'

#[directory]
#style = "bg:#DB566E"
#format = "[ $path ]($style)[$read_only]($read_only_style)"
#read_only = "  "
#read_only_style = "black bg:#DB566E"
#truncation_length = 0
#truncate_to_repo = false

## Here is how you can shorten some long paths by text replacement
#[directory.substitutions]
#"Documents" = " "
#"Downloads" = " "
#"Pictures"  = " "
#"Videos"    = "辶"
#"Music"     = " "
## Keep in mind that the order matters. For example:
## "Important Documents" = "  "
## will not be replaced, because "Documents" was already substituted before.
## So either put "Important Documents" before "Documents" or use the substituted version:
## "Important  " = "  "

#[c]
#symbol = " "
#style = "black bg:#86BBD8"
#format = '[ ](fg:#86BBD8)[ $symbol ($version) ]($style)[](fg:#86BBD8)'

#[docker_context]
#symbol = " "
#style = "black bg:#06969A"
#format = '[ ](fg:#06969A)[ $symbol $context ]($style)[](fg:#06969A)'

#[git_branch]
#symbol = ""
#style = "black bg:#FF9E64"
#format = '[ ](fg:#FF9E64)[ $symbol $branch ]($style)'

#[git_status]
#style = "black bg:#FF9E64"
#format = '[$all_status$ahead_behind ]($style)[](fg:#FF9E64)'

#[golang]
#symbol = " "
#style = "black bg:#86BBD8"
#format = '[ ](fg:#86BBD8)[ $symbol ($version) ]($style)[](fg:#86BBD8)'

#[haskell]
#symbol = " "
#style = "black bg:#86BBD8"
#format = '[ ](fg:#86BBD8)[ $symbol ($version) ]($style)[](fg:#86BBD8)'

#[java]
#symbol = " "
#style = "black bg:#86BBD8"
#format = '[ ](fg:#86BBD8)[ $symbol ($version) ]($style)[](fg:#86BBD8)'

#[nodejs]
#symbol = ""
#style = "black bg:#86BBD8"
#format = '[ ](fg:#86BBD8)[ $symbol ($version) ]($style)[](fg:#86BBD8)'

#[rust]
#symbol = ""
#style = "black bg:#86BBD8"
#format = '[ ](fg:#86BBD8)[ $symbol ($version) ]($style)[](fg:#86BBD8)'

#[lua]
#symbol = ""
#style = "black bg:#86BBD8"
#format = '[ ](fg:#86BBD8)[ $symbol ($version) ]($style)[](fg:#86BBD8)'

#[python]
#symbol = ""
#style = "black bg:#86BBD8"
#format = '[ ](fg:#86BBD8)[ $symbol ($version) ]($style)[](fg:#86BBD8)'

#[sudo]
#disabled = false
#format = "[S](yellow bold)"

#[status]
#disabled = false
#format = "[$status ↵](red)"
